name: caller_worklfow
on:
  workflow_dispatch:
    inputs:
      release_date:
        description: $(date +%Y%m%d%H%M%S )
        type: string
        default: $(date +%Y%m%d%H%M%S )
        
        
  
jobs:
  build:
    name: Step1
    uses: jkumarsahoo/testproject/.github/workflows/reusable_workflow.yml@main
    secrets:
      my-secret: ${{ secrets.PROD_SPN_SECRET }}
    with:
      my-input:  ${{ secrets.PROD_SPN_SECRET }}
