name: called_wf1
 # echo 'use-deployment-setting-file: ${{ fromJson(needs.call_json.outputs.json).use-deployment-setting-file }}'
on:
  workflow_call:
    inputs:
      solution_names:
        description: solution names
        required: true
        type: string
      target_env:
        description: target environment TEST/UAT/PROD
        required: true
        type: string
      use_deployment_setting_file:
        description: use deployment file TRUE/FLASE
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Get Deployment settings details
      if: inputs.use_deployment_setting_file == 'true'
      run: |
       echo 'deployment_setting_file_path=solutions/${{ inputs.solution_names }}/deploymentsettings/deploymentsettings_$ {{  github.event.inputs.target_env}}.json'
  
    - name: print
      run: |
          echo '${{ inputs.solution_names }}'
          echo '${{ inputs.target_env }}'
           echo '${{ inputs.use_deployment_setting_file }}'
         
