name: called_wf1
 # echo 'use-deployment-setting-file: ${{ fromJson(needs.call_json.outputs.json).use-deployment-setting-file }}'
on:
  workflow_call:
    inputs:
      solution_names:
        description: solution names
        required: true
        type: string
      target_env:
        description: target environment TEST/UAT/PROD
        required: true
        type: string
      use-deployment-setting-file:
        description: use deployment file TRUE/FLASE
        required: true
        type: string

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo '${{ inputs.solution_names }}
          echo '${{ inputs.target_env }}
           echo '${{ inputs.use-deployment-setting-file }}
         
