name: called_wf1
 # echo 'use-deployment-setting-file: ${{ fromJson(needs.call_json.outputs.json).use-deployment-setting-file }}'
on:
  workflow_call:
    inputs:
      solution_names:
        description: solution names
        required: true
        type: string
      target_env:
        description: target environment TEST/UAT/PROD
        required: true
        type: string
      use_deployment_setting_file:
        description: use deployment file TRUE/FLASE
        required: true
        type: string
        
      solution_details:
        description: deployment settings details for solutions
        required: true
        type: string

jobs:
  job1:
    strategy:
     max-parallel: 1
     matrix:
      solution_name: ${{ fromJSON(github.event.inputs.solution_names) }}
    runs-on: ubuntu-latest
    steps:
    - name: Get deployment settings details1
      run: |
       echo '${{ inputs.solution_details }}' > target_details.json
       echo 'use_deployment_settings_file1=$(jq -r '."MSE360EnvironmentVariables"."use_deployment_settings_file"' target_details.json)'  >> $GITHUB_ENV
       echo ${use_deployment_settings_file1}
      
       
    - name: Get Deployment settings details
      if: ${{ env.inner_val }} == 'true'
      run: |
       echo 'deployment_setting_file_path=solutions/${{ matrix.solution_name }}/deploymentsettings/deploymentsettings_${{  github.event.inputs.target_env}}.json' >> $GITHUB_ENV
  
    - name: print
      run: |
          echo '${{ inputs.solution_names }}'
           echo '${{ matrix.solution_name }}'
          echo '${{ inputs.target_env }}'
           echo '${{ inputs.use_deployment_setting_file }}'
           echo '${{ env.deployment_setting_file_path }}'
           echo '${{ env.inner_val }}'
           echo ${{ env.use_deployment_settings_file1 }}
           echo ${use_deployment_settings_file1}
          
         
