name: date_workflow
on:
  workflow_dispatch:
  
jobs:
  date-format:
    runs-on: ubuntu-latest
    steps:
    - 
      run: |
        echo "release_date=$(date + %Y%m%d%h)" >> $GITHUB_ENV
        echo "date is: ${{ env.release_date }}"
        
        
    
