name: if_check

on:
  workflow_dispatch:
    inputs:
      SPN_Environment:
        description: "SIT or UAT or PROD"
        type: choice
        required: true
        options: 
        - SIT_SPN_SECRET
        - UAT_SPN_SECRET
        - PROD_SPN_SECRET
env: 
  Target_Env_Secret: Dummy
  
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      some_var: ${{ steps.step1.outputs.some_var }}
    # The Secrect Actions GitHub example has three steps
    steps:
      
      # Show how to print unmasked GitHub secrets to the console
      - if: ${{ inputs.SPN_Environment == 'SIT_SPN_SECRET' }}
        id: step1
        run: |
         echo ${{ secrets.SIT_SPN_SECRET }} | sed 's/./& /g'
         #echo "Target_Env_Secret = ${{ secrets.SIT_SPN_SECRET }}" >> $GITHUB_OUTPUT
         echo "::set-output name=some_var::${{ secrets.SIT_SPN_SECRET }}" >> $GITHUB_OUTPUT
      - if: ${{ inputs.SPN_Environment == 'UAT_SPN_SECRET' }}
        run: |
         echo ${{ secrets.UAT_SPN_SECRET }} | sed 's/./& /g'
         Target_Env_Secret = ${{ secrets.UAT_SPN_SECRET }} >> $GITHUB_OUTPUT
      - if: ${{ inputs.SPN_Environment == 'PROD_SPN_SECRET' }}
        run: |
         echo ${{ secrets.PROD_SPN_SECRET }} | sed 's/./& /g'
         Target_Env_Secret = ${{ secrets.PROD_SPN_SECRET }} >> $GITHUB_OUTPUT
  job2:
    needs: job1
    uses: jkumarsahoo/testproject/.github/workflows/reusable_workflow.yml@main
    secrets:
      TARGET_ENV_SECRET: ${{ needs.job1.outputs.Target_Env_Secret }}
    

     

    
