name: if_condition

on:
  workflow_dispatch:
    inputs:
      SPN_Environment:
        description: "SIT or UAT or PROD"
        type: choice
        required: true
        options: 
        - SIT_SPN_SECRET
        - UAT_SPN_SECRET
        - PROD_SPN_SECRET
env: 
  Target_Env_Secret: Dummy
  
jobs:
  job2:
    uses: jkumarsahoo/testproject/.github/workflows/reusable_workflow.yml@latest
    with:
      env_name: $SPN_ENV
    secrets:
      TARGET_ENV_SECRET: $Target_Env_Secret 
    

     

    
