name: reusable_workflow_load_config
on: 
    workflow_call:
        inputs:
            solution_name:
                description: 'Solution name'
                type: string
                required: true
        outputs:
            json:
                description: 'Returning JSON output for target environment'
                value: ${{ jobs.load_config_json.outputs.json }}
jobs:
    load_config_json:
        runs-on: ubuntu-latest
        outputs:
            json: ${{ steps.step_load_config_json.outputs.json }}
        steps:
        - uses: actions/checkout@v3
        - id: step_load_config_json
          name: "Load config JSON"
          shell: bash
          run: |
            # read config file
            content=$(cat solutions/MSE360EnvironmentVariables/deploymentsettings/deploymentsettings_${{ github.event.inputs.target_env }}.json | jq '."${{ github.event.inputs.solution_name }}"')
            # remove multi lines
            content="${content//'%'/'%25'}"   
            content="${content//$'\n'/''}"   
            content="${content//$'\r'/'%0D'}"  
            # setting output
            echo "json=${content}" >> $GITHUB_OUTPUT 
            echo 'json'
            echo  '${content}'
        
