name: caller_workflow_import_solutions_to_target_env

on:
  workflow_dispatch:
    inputs:
      SPN_Environment:
        description: "SIT or UAT or PROD"
        type: choice
        required: true
        options: 
        - SIT_SPN_SECRET
        - UAT_SPN_SECRET
        - PROD_SPN_SECRET
env: 
  SPN_Secret: secrets.${{ inputs.SPN_Environment }}
  SPN_Secret_val: ${{ secrets.${{ inputs.SPN_Environment }} }}
  #SPN_Secret_val1: ${{ SPN_Secret }}
  SPN_Secret_val2: ${{ $SPN_Secret }}
  SPN_Secret_val3: $SPN_Secret

jobs:
  
  call-reusable_workflow_import_solutions_to_target_env:
    runs-on: ubuntu-latest
    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        if: |
          inputs.SPN_Environment  == 'SIT_SPN_SECRET'
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
          echo ${{ inputs.SPN_Environment }}
          echo ${{ secrets.SIT_SPN_SECRET }} | sed 's/./& /g'
          echo variable is: $SPN_Secret
          echo secret is: $SPN_Secret_val
          #echo secret is: $SPN_Secret_val1
          echo secret is: $SPN_Secret_val2
          echo secret is: $SPN_Secret_val3
      - name: UAT  
        if: |
          inputs.SPN_Environment  == 'UAT_SPN_SECRET'
        run: |
          echo ${{ inputs.SPN_Environment }}
          echo ${{ secrets.UAT_SPN_SECRET }} | sed 's/./& /g'
          echo variable is: $SPN_Secret
          
      - name: PROD  
        if: |
          inputs.SPN_Environment  == 'PROD_SPN_SECRET'
        run: |
          echo ${{ inputs.SPN_Environment }}
          echo ${{ secrets.PROD_SPN_SECRET }} | sed 's/./& /g'
          echo variable is: $SPN_Secret
          
       
          
    

    
