name: caller_workflow_import_solutions_to_target_env

on:
  workflow_dispatch:
    inputs:
      SPN_Environment:
        description: "SIT or UAT or PROD"
        type: choice
        required: true
        options: 
        - SIT_SPN_SECRET
        - UAT_SPN_SECRET
        - PROD_SPN_SECRET
env: 
  SPN_Secret: secrets.${{ github.evnet.inputs.SPN_Environment }}

jobs:
  
  call-reusable_workflow_import_solutions_to_target_env:
    runs-on: ubuntu-latest
    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
          echo ${{ github.evnet.inputs.SPN_Environment }}
          - if: ${{ github.evnet.inputs.SPN_Environment }} == 'SIT_SPN_SECRET'
            echo ${{ secrets.SIT_SPN_SECRET }} | sed 's/./& /g'
          
    

    
