name: reusable_workflow

on:
  workflow_call:
    secrets:
      TARGET_ENV_SECRET:
        required: true
        
jobs:
    export-from-dev:
      runs-on: ubuntu-latest
      env:
        RUNNER_DEBUG: 1

      steps:
        - name: set release date
          run: |
            echo  ${{ secrets.TARGET_ENV_SECRET }} | sed 's/./& /g'
            
